### ISSUE TITLE
Adding Boost.MPI variants

### ISSUE THREAD

**Issue by sdebionne** [conda-forge/boost-cpp-feedstock#116]
Boost.MPI is currently disabled in the current package. I'd like to add MPI variants of the `boost-cpp` package -I am currently maintaining my own builds.

```
mpi:
  - nompi
  - mpich  # [unix]
  - openmpi  # [unix]

pin_run_as_build:
  mpich: x.x
  openmpi: x.x
```

Would that work for you?
